[2024-04-11 19:53:19,920] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:53:19,925] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:53:19,927] INFO _log() L96    * Restarting with stat - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:53:21,911] WARNING _log() L96    * Debugger is active! - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:53:21,917] INFO _log() L96    * Debugger PIN: 442-501-179 - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:54:06,980] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 19:54:06] "[31m[1mGET /ordem?id= HTTP/1.1[0m" 405 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:54:09,262] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 19:54:09] "[31m[1mGET /ordem?id=1 HTTP/1.1[0m" 405 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:54:32,644] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 19:54:32] "[31m[1mGET /ordem HTTP/1.1[0m" 405 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:55:28,462] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 19:55:28] "[33mGET /ordem1 HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:55:51,868] WARNING get_ordens() L86   Erro ao consultar a ordem de produção 'Ordem' object is not iterable - call_trace=C:\Users\Felipe Pinto\OneDrive\Documentos\Faculdade\PUC-RIO\pos-fullstack-basico\controller.py L86  
[2024-04-11 19:55:51,869] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 19:55:51] "[31m[1mGET /ordem/1 HTTP/1.1[0m" 400 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:57:07,919] WARNING get_ordens() L86   Erro ao consultar a ordem de produção 'Ordem' object is not iterable - call_trace=C:\Users\Felipe Pinto\OneDrive\Documentos\Faculdade\PUC-RIO\pos-fullstack-basico\controller.py L86  
[2024-04-11 19:57:07,921] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 19:57:07] "[31m[1mGET /ordem/1 HTTP/1.1[0m" 400 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:57:54,232] WARNING get_ordens() L86   Erro ao consultar a ordem de produção 'Ordem' object is not iterable - call_trace=C:\Users\Felipe Pinto\OneDrive\Documentos\Faculdade\PUC-RIO\pos-fullstack-basico\controller.py L86  
[2024-04-11 19:57:54,591] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 19:57:54] "[31m[1mGET /ordem/1 HTTP/1.1[0m" 400 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:58:26,546] INFO _log() L96    * Detected change in 'C:\\Users\\Felipe Pinto\\OneDrive\\Documentos\\Faculdade\\PUC-RIO\\pos-fullstack-basico\\controller.py', reloading - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:58:28,057] INFO _log() L96    * Restarting with stat - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:58:30,020] WARNING _log() L96    * Debugger is active! - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 19:58:30,027] INFO _log() L96    * Debugger PIN: 442-501-179 - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:02:59,554] INFO _log() L96    * Detected change in 'C:\\Users\\Felipe Pinto\\OneDrive\\Documentos\\Faculdade\\PUC-RIO\\pos-fullstack-basico\\controller.py', reloading - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:03:03,377] INFO _log() L96    * Restarting with stat - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:03:05,352] WARNING _log() L96    * Debugger is active! - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:03:05,358] INFO _log() L96    * Debugger PIN: 442-501-179 - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:03:23,393] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:03:23] "GET /ordem/1 HTTP/1.1" 200 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:03:46,992] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:03:46] "GET /ordem/1 HTTP/1.1" 200 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:04:38,144] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:04:38] "GET /ordem/1 HTTP/1.1" 200 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:10:10,925] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:10:10] "[31m[1mGET /ordem HTTP/1.1[0m" 405 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:10:13,293] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:10:13] "[33mGET /ordem/ HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:10:16,399] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:10:16] "[31m[1mGET /ordem HTTP/1.1[0m" 405 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:11:28,347] INFO _log() L96    * Detected change in 'C:\\Users\\Felipe Pinto\\OneDrive\\Documentos\\Faculdade\\PUC-RIO\\pos-fullstack-basico\\schemas\\ordem.py', reloading - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:11:31,566] INFO _log() L96    * Restarting with stat - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:11:33,546] WARNING _log() L96    * Debugger is active! - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:11:33,551] INFO _log() L96    * Debugger PIN: 442-501-179 - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:11:41,418] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:11:41] "[31m[1mGET /ordem HTTP/1.1[0m" 405 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:11:54,862] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:11:54] "[31m[1mGET /ordem HTTP/1.1[0m" 405 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:17:36,375] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:17:36] "[33mGET /ordem/ HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:17:40,056] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:17:40] "GET /ordem/1 HTTP/1.1" 200 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:17:42,293] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:17:42] "[33mGET /ordem/ HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:20:47,671] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:20:47] "GET /ordem/1 HTTP/1.1" 200 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:20:48,911] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:20:48] "GET /ordem/0 HTTP/1.1" 200 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:21:27,641] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:21:27] "GET /ordem/1 HTTP/1.1" 200 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:22:24,467] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:22:24] "GET /ordem/1 HTTP/1.1" 200 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:22:44,511] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:22:44] "GET /ordem/1 HTTP/1.1" 200 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:22:48,017] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:22:48] "[33mGET /ordem/ HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:23:19,343] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:23:19] "[33mGET /ordem/ HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:23:50,103] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:23:50] "[33mGET /ordem/ HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:24:35,439] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:24:35] "[33mGET /ordem/ HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:24:51,581] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:24:51] "[33mGET /ordem/ HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:25:22,167] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:25:22] "[33mGET /ordem/ HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:26:00,191] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:26:00] "[33mGET /ordem/ HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:26:23,037] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:26:23] "[33mGET /ordem/ HTTP/1.1[0m" 404 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:27:02,734] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:27:02] "GET /ordem/0 HTTP/1.1" 200 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
[2024-04-11 20:27:06,833] INFO _log() L96   127.0.0.1 - - [11/Apr/2024 20:27:06] "GET /ordem/0 HTTP/1.1" 200 - - call_trace=c:\Python39\lib\site-packages\werkzeug\_internal.py L96  
